

artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_url: https://github.com/gbiamgaurav/github_datasets/raw/main/income_inequality.zip
  local_data_file: artifacts/data_ingestion/income_data.zip
  unzip_dir: artifacts/data_ingestion


data_transformation:
  root_dir: artifacts/data_transformation
  data_path: artifacts/data_ingestion/income_inequality_prediction.csv
  preprocessor_path: artifacts/data_transformation/preprocessor.joblib


model_trainer:
  root_dir: artifacts/model_trainer
  train_data_path: artifacts/data_transformation/train_resampled.csv
  test_data_path: artifacts/data_transformation/test.csv
  model_name: income_model.joblib


